/*
 * This source file was generated by the Gradle 'init' task
 */
package org.api

import io.ktor.server.application.Application
import org.api.controller.configureRouting

class App {
    fun greeting(){
        print("This is to satisfy a test")
    }

    fun start(args: Array<String>) {
        // Load configuration from application.yaml
        io.ktor.server.netty.EngineMain.main(args)
    }
}

fun main(args: Array<String>) {
    //App().start(args)
    io.ktor.server.netty.EngineMain.main(args)
}


fun Application.module() {
    configureRouting()
}

