/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class Api {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(Api().greeting)
}
